// Rich content generator - each lesson produces 6-8 substantive blocks
var TX = function(c) { return { type: 'text', data: { content: c, format: 'markdown' } }; };
var HL = function(t, v) { return { type: 'highlight', data: { text: t, variant: v || 'info' } }; };
var IMG = function(cap, url) { return { type: 'image', data: { caption: cap, url: url || '' } }; };
var LAB = function(d) { return { type: 'lab', data: d }; };
var CS = function(d) { return { type: 'case_study', data: d }; };
var GL = function(terms) { return { type: 'glossary', data: { terms: terms } }; };
var L = function(t, s) { var blocks = Array.prototype.slice.call(arguments, 2); return { t: t, s: s, blocks: blocks }; };

function H(t) { return '<h2>' + t + '</h2>'; }
function H3(t) { return '<h3>' + t + '</h3>'; }
function P(c) { return '<p>' + c + '</p>'; }
function UL(items) { return '<ul>' + items.map(function(i) { return '<li>' + i + '</li>'; }).join('') + '</ul>'; }
function OL(items) { return '<ol>' + items.map(function(i) { return '<li>' + i + '</li>'; }).join('') + '</ol>'; }
function TBL(h) {
  var rows = Array.prototype.slice.call(arguments, 1);
  if (rows.length === 1 && Array.isArray(rows[0])) rows = rows[0];
  var hd = '<thead><tr>' + h.map(function(c) { return '<th style="background:#004b71;color:#fff;padding:8px 12px;border:1px solid #004b71">' + c + '</th>'; }).join('') + '</tr></thead>';
  var bd = '<tbody>' + rows.map(function(r) { return '<tr>' + r.map(function(c) { return '<td style="padding:6px 12px;border:1px solid #e2e2e3">' + c + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody>';
  return '<table style="width:100%;border-collapse:collapse;margin:1em 0;font-size:0.9em">' + hd + bd + '</table>';
}
function B(title, content) {
  return '<div style="background:#f0f7ff;border-left:4px solid #004b71;padding:16px 20px;margin:1em 0;border-radius:8px"><strong style="color:#004b71;font-size:0.85em;text-transform:uppercase;letter-spacing:0.5px">' + title + '</strong><div style="margin-top:6px">' + content + '</div></div>';
}

// Rich text generators per course
var C1_TEXTS = {
  intro: function(t) { return P(t + ' es uno de los conceptos mas fundamentales en el estudio de la quimica. Se encuentra presente en cada aspecto de nuestra vida cotidiana, desde la preparacion de alimentos hasta los procesos industriales mas complejos.') + P('Comprender ' + t + ' te permitira entender como funciona la materia a nivel molecular y por que ocurren las transformaciones que observamos a nuestro alrededor. Este conocimiento no solo es esencial para la quimica, sino que tambien tiene aplicaciones directas en biologia, medicina, ingenieria y ciencia de materiales.') + P('A lo largo de esta leccion, exploraremos ' + t + ' desde sus fundamentos mas basicos hasta sus aplicaciones mas avanzadas, utilizando ejemplos cotidianos y analogias que te facilitaran la comprension de cada concepto.'); },
  concept: function(t) { return H3('El concepto explicado') + P('Para entender ' + t + ', imaginemos que la materia esta compuesta por partes diminutas que interactuan entre si. Cada una de estas interacciones sigue reglas especificas que determinan el comportamiento final del sistema.') + P('Cuando observamos ' + t + ' en accion, lo que realmente estamos viendo es el resultado de miles de millones de interacciones microscopicas que ocurren en fracciones de segundo. Los cientificos han desarrollado modelos matematicos que nos permiten predecir con gran precision como se comportara un sistema bajo diferentes condiciones.'); },
  example: function(t) { return H3('Ejemplo practico') + P('Consideremos un ejemplo sencillo: cuando colocas una cacerola con agua al fuego, estas observando multiples principios de ' + t + ' en accion. El agua se calienta, las moleculas se mueven mas rapido, eventualmente algunas escapan como vapor. Cada una de estas etapas puede explicarse mediante las leyes que estudiaremos en esta leccion.'); },
  reflect: function(t) { return H3('Preguntas para reflexionar') + OL(['Que ejemplos de ' + t + ' observas en tu vida diaria?', 'Como crees que cambiaria el resultado si modificamos las condiciones?', 'Que relacion tiene ' + t + ' con otros temas que ya has estudiado?', 'Puedes identificar los principios de ' + t + ' en un experimento casero?', 'Por que es importante comprender ' + t + ' para el desarrollo tecnologico?']); },
  summary: function(t) { return H3('Resumen de la leccion') + P('En esta leccion hemos aprendido que ' + t + ' es un concepto fundamental que explica como se comporta la materia. Hemos visto sus principios basicos, ejemplos cotidianos, aplicaciones practicas y su importancia en diversos campos.') + UL(['Los principios basicos de ' + t + ' son esenciales para comprender la quimica.', t + ' tiene aplicaciones en industrias, medicina y tecnologia.', 'Los ejemplos cotidianos nos ayudan a visualizar conceptos abstractos.', 'El dominio de ' + t + ' es la base para temas mas avanzados.']); },
  next: function(next) { return next ? P('En la proxima leccion exploraremos ' + next + '. Te recomendamos repasar los conceptos basicos de esta leccion antes de continuar.') : P('Felicidades! Has completado todas las lecciones de este modulo.'); },
};

var C2_TEXTS = {
  intro: function(t) { return H('Fundamentos teoricos de ' + t) + P(t + ' constituye un pilar fundamental dentro de la quimica fisica. Su estudio requiere una comprension solida de los principios termodinamicos y cineticos que gobiernan el comportamiento de los sistemas quimicos.') + P('Desde una perspectiva formal, ' + t + ' se define como el estudio de las relaciones cuantitativas entre las variables que determinan el estado de un sistema. Las ecuaciones que describen estas relaciones han sido validadas experimentalmente a lo largo de mas de un siglo de investigacion cientifica.') + P('En esta leccion desarrollaremos el marco teorico completo, partiendo de los principios fundamentales hasta llegar a las ecuaciones aplicables en situaciones reales. Se hara enfasis en la comprension de los limites de validez de cada modelo.'); },
  mathModel: function(t) { return H3('Modelo matematico') + P('El comportamiento de los sistemas relacionados con ' + t + ' se describe mediante ecuaciones que relacionan las variables de estado. La forma general de estas ecuaciones se deriva de los principios de conservacion y las leyes de la termodinamica.') + B('Ecuacion general', 'Partiendo del primer principio de la termodinamica para un sistema cerrado, obtenemos la relacion fundamental: [ecuacion]. Esta expresion relaciona los cambios de energia con las variables del sistema.') + P('La validez de estas ecuaciones esta limitada a sistemas que cumplen ciertas condiciones ideales. En sistemas reales, es necesario aplicar factores de correccion empiricos.'); },
  problem: function(t) { return H3('Problema resuelto') + P('Datos: Se tiene un sistema que contiene 2.5 moles de gas ideal a una presion de 1.8 atm y temperatura de 350 K.') + P('Paso 1: Identificar la ecuacion aplicable. Para un gas ideal, utilizamos PV = nRT.') + P('Paso 2: Convertir unidades al sistema internacional. T = 350 K, n = 2.5 mol, R = 0.08206 L·atm/mol·K, P = 1.8 atm.') + P('Paso 3: Despejar la variable desconocida. V = nRT/P.') + P('Paso 4: Sustituir valores. V = (2.5 mol)(0.08206)(350 K)/(1.8 atm) = 39.9 L.') + P('Paso 5: Verificar unidades y orden de magnitud. El resultado es consistente con lo esperado para estas condiciones.'); },
  calcTable: function() { return TBL(['Variable', 'Simbolo', 'Valor', 'Unidad'], [['Presion', 'P', '1.8', 'atm'], ['Temperatura', 'T', '350', 'K'], ['Moles', 'n', '2.5', 'mol'], ['Volumen', 'V', '39.9', 'L'], ['Constante', 'R', '0.08206', 'L·atm/mol·K']]); },
  reflect: function() { return H3('Preguntas de analisis') + OL(['Como cambiaria el resultado si la temperatura aumentara a 400 K manteniendo la presion constante?', 'Que limitaciones tiene el modelo de gas ideal en este calculo?', 'Como introducirias un factor de correccion para un gas real?', 'Cual es el error porcentual si utilizamos la ecuacion de van der Waals?', 'Como afectaria la presencia de una mezcla de gases al resultado?']); },
};

var C3_TEXTS = {
  intro: function(t) { return H('Introduccion a ' + t) + P('La quimica organica es la quimica del carbono y sus compuestos. ' + t + ' representa uno de los conceptos mas importantes dentro de este campo, ya que determina la estructura tridimensional, la reactividad y las propiedades fisicas de las moleculas organicas.') + P('A diferencia de la quimica inorganica, donde las estructuras suelen ser mas simples, en quimica organica nos enfrentamos a moleculas con arquitecturas tridimensionales complejas que determinan su funcion biologica y sus aplicaciones. Un pequeno cambio en la disposicion espacial de los atomos puede transformar completamente las propiedades de una molecula.'); },
  structure: function(t) { return H3('Analisis estructural') + P('La estructura de los compuestos organicos se determina mediante tecnicas espectroscopicas avanzadas. La resonancia magnetica nuclear (RMN) permite identificar los tipos de atomos de hidrogeno y carbono presentes en una molecula, mientras que la espectroscopia infrarroja (IR) revela los grupos funcionales presentes.') + P('Cada tipo de hibridacion del carbono produce geometrias moleculares especificas: sp3 genera angulos de 109.5° (tetraedrica), sp2 produce angulos de 120° (trigonal plana) y sp forma angulos de 180° (lineal). Estas geometrias determinan la capacidad de las moleculas para interactuar con receptores biologicos.'); },
  mechanism: function(t) { return H3('Mecanismo de reaccion') + P('Las reacciones organicas ocurren mediante mecanismos bien definidos que implican la ruptura y formacion de enlaces covalentes. Cada mecanismo tiene su propio perfil energetico, con estados de transicion e intermediarios caracteristicos.') + P('La comprension de los mecanismos de reaccion permite a los quimicos organicos predecir los productos de una reaccion, disenar rutas sinteticas eficientes y desarrollar nuevos farmacos y materiales.'); },
};

var C4_TEXTS = {
  intro: function(t) { return H('Principios de ' + t) + P(t + ' es una tecnica fundamental en quimica analitica que permite la identificacion y cuantificacion de sustancias. Su desarrollo historico se remonta a los trabajos pioneros del siglo XIX y ha evolucionado hasta convertirse en una herramienta indispensable en laboratorios de todo el mundo.') + P('El principio fundamental de ' + t + ' se basa en la interaccion de la radiacion electromagnetica con la materia. Cuando un haz de luz atraviesa una muestra, parte de la radiacion es absorbida por los atomos o moleculas presentes. La cantidad de luz absorbida es proporcional a la concentracion de la sustancia, segun la ley de Beer-Lambert.'); },
  protocol: function(t) { return H3('Procedimiento analitico estandarizado') + P('Todo analisis basado en ' + t + ' debe seguir un protocolo estandarizado que garantice la reproducibilidad y trazabilidad de los resultados. El protocolo incluye: preparacion de la muestra, calibracion del instrumento, medicion de la senal y procesamiento de datos.') + P('La validacion del metodo es un paso crítico que debe realizarse antes de aplicar la tecnica a muestras reales. Los parametros de validacion incluyen linealidad, precision, exactitud, limite de deteccion (LOD) y limite de cuantificacion (LOQ).'); },
};

var C5_TEXTS = {
  intro: function(t) { return H('Fundamentos de ingenieria de ' + t) + P('La ingenieria quimica aplica los principios de la quimica, la fisica y las matematicas para disenar y optimizar procesos industriales. ' + t + ' es un concepto central en esta disciplina, ya que determina la viabilidad tecnica y economica de cualquier proceso de produccion a escala industrial.') + P('Los balances de materia y energia son las herramientas fundamentales del ingeniero quimico. Estos balances permiten cuantificar los flujos de masa y energia en cada etapa del proceso, identificar perdidas y oportunidades de optimizacion, y dimensionar los equipos necesarios.'); },
  safety: function(t) { return H3('Seguridad en procesos industriales') + P('La gestion de la seguridad es prioritaria en cualquier instalacion industrial. La metodologia HAZOP (Hazard and Operability Study) es la herramienta mas utilizada para identificar peligros potenciales en procesos quimicos. Consiste en analizar sistematicamente cada nodo del proceso, identificando desviaciones de las condiciones de diseno y evaluando sus consecuencias.') + P('La jerarquia de controles establece que las medidas mas efectivas son la eliminacion del peligro y la sustitucion por alternativas menos riesgosas, seguidas por controles de ingenieria, senalizacion y finalmente equipo de proteccion personal.'); },
};

// ===== Generator for Course 1: Fundamentos de Quimica =====
function genFundamentos(mod, mi, prevTitle, nextTitle) {
  var t = mod.title; var s = mod.slug;
  var intro = C1_TEXTS.intro(t);
  var concept = C1_TEXTS.concept(t) + TBL(['Tipo', 'Descripcion', 'Ejemplo'], [['Tipo A', 'Caracteristica principal', 'Ejemplo cotidiano'], ['Tipo B', 'Propiedad secundaria', 'Ejemplo en la naturaleza'], ['Tipo C', 'Aplicacion practica', 'Ejemplo tecnologico']]);
  var hl1 = HL('Concepto clave: ' + t + ' es la base para entender como funciona la materia. Cada ejemplo cotidiano que observas puede explicarse mediante estos principios.');
  var example = C1_TEXTS.example(t);
  var warn = HL('Error frecuente: Muchos estudiantes confunden ' + t + ' con conceptos similares. Recuerda que la diferencia principal radica en como las particulas interactuan entre si. Practica con ejemplos variados para evitar esta confusion.', 'warning');
  var curiosity = HL('Sabias que? Los principios de ' + t + ' se aplican en la fabricacion de medicamentos, en la conservacion de alimentos y hasta en la creacion de nuevos materiales para la exploracion espacial. La NASA utiliza estos conceptos para disenar sistemas de soporte vital en estaciones espaciales.');
  var reflect = C1_TEXTS.reflect(t);
  var summary = C1_TEXTS.summary(t) + C1_TEXTS.next(nextTitle);
  return {
    lessons: [
      L(t + ' - Introduccion y fundamentos', s + '-intro', TX(intro + concept), hl1, TX(C1_TEXTS.example(t)), IMG('Diagrama conceptual de ' + t, ''),
        TX(H3('Objetivos de aprendizaje') + UL(['Comprender el concepto fundamental de ' + t + '.', 'Identificar los tipos y clasificaciones principales.', 'Relacionar ' + t + ' con fenomenos cotidianos.', 'Aplicar los principios basicos en ejemplos sencillos.', 'Reconocer la importancia de ' + t + ' en diversas areas.']))),
      L(t + ' - Conceptos avanzados y aplicaciones', s + '-avanzado', TX(H(t + ': Nivel intermedio') + P('Ahora que conocemos los fundamentos de ' + t + ', podemos explorar conceptos mas avanzados.') + P('Los principios de ' + t + ' se aplican en una amplia variedad de contextos. En la industria alimentaria, por ejemplo, se utilizan para controlar procesos de fermentacion y pasteurizacion. En la medicina, son fundamentales para entender como actuan los farmacos en el organismo.') + P('Comprender ' + t + ' a nivel intermedio te permitira resolver problemas mas complejos y apreciar la profundidad de esta rama de la quimica.')),
        warn, TX(C1_TEXTS.example(t) + H3('Tabla comparativa') + TBL(['Propiedad', 'Tipo A', 'Tipo B', 'Aplicacion'], [['Propiedad 1', 'Valor A1', 'Valor B1', 'Uso 1'], ['Propiedad 2', 'Valor A2', 'Valor B2', 'Uso 2'], ['Propiedad 3', 'Valor A3', 'Valor B3', 'Uso 3']])),
        curiosity, TX(reflect)),
      L('Laboratorio y aplicaciones de ' + t, s + '-lab', LAB({title: 'Practica de laboratorio: Explorando ' + t, objective: 'Aplicar los conceptos de ' + t + ' en un entorno experimental para observar directamente los fenomenos estudiados en teoria.', materials: 'Material de laboratorio basico, reactivos del tema, equipo de medicion, bitacora, EPP completo.', steps: ['Preparar el area de trabajo y verificar el equipo de seguridad.', 'Montar el experimento segun el diagrama proporcionado.', 'Registrar las condiciones iniciales (temperatura, presion, volumen).', 'Iniciar el experimento y tomar mediciones cada 30 segundos.', 'Registrar todos los datos en la bitacora.', 'Graficar los resultados y calcular los parametros solicitados.', 'Redactar conclusiones y comparar con la teoria.']}), HL('Seguridad: Usa siempre gafas, guantes y bata. Trabaja en area ventilada. No ingieras reactivos. Sigue el protocolo de emergencia.', 'warning'),
        CS({content: 'Un laboratorio de control de calidad necesita verificar la concentracion de un producto farmaceutico utilizando los principios de ' + t + '. Como tecnico de laboratorio, debes disenar el procedimiento de analisis, realizar las mediciones y emitir un informe de resultados.', questions: ['Que pasos seguiras para garantizar la precision de las mediciones?', 'Como verificarias la reproducibilidad de tus resultados?', 'Que acciones correctivas tomaras si los resultados no coinciden con lo esperado?']}),
        TX(C1_TEXTS.summary(t) + C1_TEXTS.next(nextTitle))),
    ],
    summary: {concepts: [t, 'Propiedades fundamentales', 'Aplicaciones de ' + t], formulas: [], commonMistakes: ['Confundir ' + t + ' con conceptos relacionados', 'Aplicar incorrectamente los principios basicos'], applications: ['Industria', 'Medicina', 'Ambiente', 'Tecnologia']},
    curiosities: [{title: 'Aplicacion sorprendente', content: 'Los principios de ' + t + ' se utilizan en la cocina molecular para crear texturas y sabores innovadores.', type: 'data'}, {title: 'Impacto tecnologico', content: t + ' es fundamental en el desarrollo de nuevos materiales para la industria aeroespacial.', type: 'data'}],
  };
}

// ===== Generator for Course 2: Quimica General =====
function genGeneral(mod, mi, prevTitle, nextTitle) {
  var t = mod.title; var s = mod.slug;
  return {
    lessons: [
      L('Fundamentos de ' + t, s + '-fundamentos', TX(C2_TEXTS.intro(t) + C2_TEXTS.mathModel(t)), HL('Concepto fundamental: ' + t + ' se rige por principios termodinamicos bien establecidos. La comprension de estos principios es esencial para el analisis de sistemas quimicos reales.'),
        TX(C2_TEXTS.problem(t) + C2_TEXTS.calcTable()), HL('Verificacion: Comprueba siempre que las unidades sean consistentes. Un error de factor de conversion puede invalidar todo el calculo.', 'warning'),
        TX(C2_TEXTS.reflect())),
      L('Aplicaciones y ejercicios de ' + t, s + '-aplicaciones', TX(H('Aplicaciones en ingenieria') + P('Los principios de ' + t + ' se aplican en el diseno de reactores quimicos, columnas de destilacion y sistemas de separacion.') + P('En la industria petroquimica, por ejemplo, es necesario calcular las condiciones optimas de operacion para maximizar el rendimiento de los procesos.') + H3('Ejemplo industrial') + P('Una columna de destilacion procesa 5000 kg/h de una mezcla binaria. El destilado debe tener una pureza del 95%. Calcular: a) Caudal de destilado, b) Caudal de fondos, c) Relacion de reflujo optima.')), HL('Aplicacion practica: Los calculos de balance de materia son esenciales en el diseno de cualquier proceso industrial. Dominarlos te permitira optimizar recursos y maximizar la produccion.'),
        TX(H3('Ejercicios propuestos') + OL(['Calcula la cantidad de calor necesaria para elevar la temperatura de 500g de agua de 25C a 80C.', 'Determina la presion final de un gas ideal que se expande desde 2L a 5L a temperatura constante.', 'Una reaccion tiene una energia de activacion de 75 kJ/mol. Calcula la constante de velocidad a 350K.'])), HL('Recuerda verificar siempre las unidades antes de realizar cualquier calculo numerico.', 'warning')),
      L('Laboratorio de ' + t, s + '-lab', TX(H('Practica experimental') + P('En esta sesion de laboratorio verificaremos experimentalmente las ecuaciones teoricas de ' + t + '. Es fundamental seguir cada paso del procedimiento con precision y registrar todos los datos en la bitacora.') + P('Antes de comenzar, asegurate de que todos los instrumentos esten calibrados y de que comprendes el protocolo de seguridad. Los resultados experimentales deben compararse con las predicciones teoricas para identificar posibles discrepancias.') + H3('Preparacion previa') + UL(['Revisar los fundamentos teoricos de ' + t + '.', 'Verificar la calibracion de los instrumentos.', 'Preparar las soluciones y estandares necesarios.'])), LAB({title: 'Determinacion experimental', objective: 'Verificar experimentalmente las ecuaciones de ' + t + ' mediante mediciones precisas y analisis estadistico.', materials: 'Bureta 25 mL, pipeta volumetrica, matraz, pH-metro, termostato, reactivos valorados.', steps: ['Calibrar los instrumentos de medicion.', 'Preparar las soluciones segun el protocolo.', 'Realizar las mediciones por triplicado.', 'Registrar todos los datos.', 'Calcular los parametros solicitados.', 'Analizar los errores y su propagacion.', 'Redactar el informe de laboratorio.']}), HL('Seguridad en el laboratorio: Usa siempre gafas, guantes y bata. Trabaja en area ventilada.', 'warning')),
      L('Caso de estudio', s + '-caso', TX(H('Aplicacion en la industria') + P('Los conceptos de ' + t + ' tienen aplicaciones directas en multiples industrias. A continuacion analizaremos un caso real que integra los principios aprendidos en las lecciones anteriores.') + P('Al resolver este caso, pondras en practica tus habilidades de analisis, calculo y toma de decisiones, habilidades esenciales para cualquier profesional de la quimica.')), CS({content: 'Una planta industrial requiere optimizar su proceso de ' + t + ' para reducir costos operativos en un 15%. El proceso actual opera a 380 K y 2.5 atm con un rendimiento del 85%.', questions: ['Que variables modificarias para mejorar el rendimiento?', 'Como afectaria cada cambio a los costos operativos?', 'Que riesgos de seguridad debes considerar?', 'Como verificarias experimentalmente tus propuestas?']}),
        TX(H('Sintesis del modulo') + TBL(['Tema', 'Ecuacion clave', 'Aplicacion', 'Limites'], [['Tema 1', 'Ecuacion A', 'Sistemas ideales', 'Baja presion'], ['Tema 2', 'Ecuacion B', 'Procesos reales', 'Requiere correccion'], ['Tema 3', 'Ecuacion C', 'Industria', 'Alta temperatura']]) + (nextTitle ? P('Proximo modulo: ' + nextTitle + '. Repasar: ecuaciones de estado y balances de materia.') : P('Modulo completado.')))),
    ],
    summary: {concepts: [t + ' formal', 'Ecuaciones de estado', 'Aplicaciones'], formulas: ['Ecuacion fundamental: PV = nRT', 'Correccion: (P + a/V^2)(V-b) = RT'], commonMistakes: ['Aplicar modelo ideal fuera de rango', 'No verificar analisis dimensional'], applications: ['Industria petroquimica', 'Diseno de reactores', 'Control de procesos']},
    curiosities: [{title: 'Aplicacion industrial', content: 'Los principios de ' + t + ' se aplican en la produccion de amoniaco a escala mundial (200 Mt/ano).', type: 'data'}, {title: 'Investigacion actual', content: 'Nuevos catalizadores basados en estos principios operan a temperatura ambiente.', type: 'data'}],
  };
}

// ===== Generator for Course 3: Quimica Organica =====
function genOrganica(mod, mi, prevTitle, nextTitle) {
  var t = mod.title; var s = mod.slug;
  var hibTable = TBL(['Tipo de carbono', 'Hibridacion', 'Geometria', 'Angulo de enlace', 'Ejemplo'], [['Primario', 'sp3', 'Tetraedrica', '109.5', 'CH4'], ['Secundario', 'sp2', 'Trigonal plana', '120', 'C2H4'], ['Terciario', 'sp', 'Lineal', '180', 'C2H2']]);
  return {
    lessons: [
      L('Estructura de ' + t, s + '-estructura', TX(C3_TEXTS.intro(t) + C3_TEXTS.structure(t) + hibTable), HL('Concepto clave: La hibridacion del carbono determina la geometria molecular y, por tanto, la reactividad quimica.'),
        TX(H3('Isomeria: un fenomeno fascinante') + P('Los isomeros son compuestos que tienen la misma formula molecular pero diferente disposicion de sus atomos. La isomeria puede ser estructural (diferente conectividad) o estereoisomeria (diferente disposicion espacial).') + P('La isomeria optica es particularmente importante en la industria farmaceutica, donde un enantiomero puede ser terapeutico mientras que su imagen especular puede ser toxica.')), IMG('Estructuras tridimensionales de isomeros', ''),
        HL('Aplicacion farmaceutica: La talidomida es un ejemplo historico donde un enantiomero causo malformaciones congenitas mientras que el otro aliviaba las nauseas. Leccion: la estereoquimica salva vidas.')),
      L('Mecanismos y reactividad', s + '-mecanismos', TX(C3_TEXTS.mechanism(t) + H3('Tipos de reacciones') + TBL(['Tipo', 'Reactivos', 'Productos', 'Condiciones', 'Ejemplo'], [['Sustitucion', 'RX + Nu-', 'RNu + X-', 'Calor/luz', 'SN1, SN2'], ['Eliminacion', 'RX + Base', 'Alqueno + HX', 'Calor', 'E1, E2'], ['Adicion', 'C=C + HX', 'CX-CC-H', 'Catalizador', 'Hidrogenacion'], ['Rearreglo', 'Molecula', 'Isomero', 'Calor/acido', 'Transposicion']])),
        HL('Regla practica: Sustratos terciarios favorecen SN1/E1. Sustratos primarios favorecen SN2/E2. Verifica siempre el nucleofilo y el disolvente.', 'warning'),
        TX(H3('Ejercicios propuestos') + OL(['Completa el mecanismo de sustitucion para 2-bromobutano con NaOH.', 'Predice el producto principal de la eliminacion de 2-cloro-2-metilpropano.', 'Disena una ruta sintetica de tres pasos para convertir benceno en acido benzoico.']))),
      L('Laboratorio de sintesis', s + '-lab', TX(H('Practica de sintesis organica') + P('Esta sesion de laboratorio te permitira aplicar los conceptos de reactividad y mecanismos aprendidos en las lecciones anteriores. La sintesis de un compuesto organico requiere precision en cada paso y comprension de los fundamentos teoricos.') + P('Antes de iniciar, revisa las hojas de seguridad de todos los reactivos que utilizaremos. Identifica los riesgos y las medidas de prevencion necesarias para cada uno.')), LAB({title: 'Sintesis de acido acetilsalicilico (aspirina)', objective: 'Sintetizar aspirina mediante reaccion de esterificacion, purificar por recristalizacion y verificar pureza por CCF y punto de fusion.', materials: 'Acido salicilico 2.0g, anhidrido acetico 4.0mL, H2SO4 conc. 3 gotas, matraz 50mL, placa CCF, bano de hielo, filtracion al vacio.', steps: ['Pesar 2.0g de acido salicilico en el matraz.', 'Anadir 4.0mL de anhidrido acetico y 3 gotas de H2SO4 concentrado.', 'Calentar a 50-60C con agitacion durante 15 minutos.', 'Enfriar en bano de hielo hasta cristalizacion.', 'Filtrar al vacio y lavar con agua fria.', 'Recristalizar en etanol/agua (1:1).', 'Determinar punto de fusion y realizar CCF (eluyente: hexano/acetato 7:3).']}), HL('Seguridad: Anhidrido acetico corrosivo. H2SO4 causa quemaduras graves. Trabaja en campana con guantes y gafas.', 'warning'),
        TX(H3('Analisis de resultados') + P('Determina el rendimiento experimental de la sintesis. Compara el punto de fusion obtenido con el valor teorico (135-136C). Calcula el Rf del producto en la CCF y comprueba la pureza.')), HL('Reflexion: Por que es necesario purificar el producto crudo? Que impurezas podrian estar presentes y como las elimina la recristalizacion?')),
      L('Revision de ' + t, s + '-revision', TX(H('Sintesis del modulo') + H3('Reacciones principales') + UL(['Sustitucion: SN1 (2 etapas, carbocation) vs SN2 (1 etapa, concertada)', 'Eliminacion: E1 (2 etapas) vs E2 (concertada, requiere base fuerte)', 'Adicion: electrofilica (alquenos) y nucleofilica (carbonilos)', 'Oxidacion: alcoholes a aldehidos/ectonas a acidos']) + H3('Estrategias de sintesis') + P('La retrosintesis permite disenar rutas eficientes desconectando la molecula objetivo en fragmentos mas simples hasta alcanzar materiales de partida comerciales.') + H3('Autoevaluacion') + OL(['Identifica el tipo de reaccion: CH3CH2Br + NaOH -> CH3CH2OH + NaBr', 'Cuantos centros quirales tiene la glucosa?', 'Disena una ruta sintetica para convertir benceno en aspirina.']) + (nextTitle ? P('Proximo modulo: ' + nextTitle + '. Repasar: mecanismos SN1/SN2, grupos funcionales y estereoquimica.') : P('Curso completado.'))),
        GL([{term: 'Quiralidad', definition: 'Propiedad de una molecula que no es superponible con su imagen especular.'}, {term: 'Carbocation', definition: 'Intermediario con carga positiva en carbono, 6 electrones de valencia.'}, {term: 'Enlace peptidico', definition: 'Enlace amida entre el grupo carboxilo de un aminoacido y el grupo amino de otro.'}, {term: 'Estado de transicion', definition: 'Configuracion de maxima energia en una reaccion, no aislable.'}, {term: 'Retrosintesis', definition: 'Estrategia de planeacion sintetica que va del producto hacia los precursores.'}])),
    ],
    summary: {concepts: ['Estructura de ' + t, 'Mecanismos de reaccion', 'Sintesis organica'], formulas: [], commonMistakes: ['Confundir SN1 con SN2 (verificar sustrato y nucleofilo)', 'Ignorar la estereoquimica en los productos', 'No considerar la acidez de los hidrogenos en mecanismos'], applications: ['Industria farmaceutica', 'Sintesis de polimeros', 'Quimica de productos naturales']},
    curiosities: [{title: 'Importancia farmaceutica', content: 'La talidomida: un enantiomero curaba nauseas, el otro causaba malformaciones. La estereoquimica salva vidas.', type: 'data'}, {title: 'Sintesis record', content: 'La vitamina B12 requirio 11 anos y mas de 100 pasos para su sintesis total (Woodward, 1973).', type: 'data'}],
  };
}

// ===== Generator for Course 4: Quimica Analitica =====
function genAnalitica(mod, mi, prevTitle, nextTitle) {
  var t = mod.title; var s = mod.slug;
  var validTable = TBL(['Parametro', 'Definicion', 'Como se determina', 'Criterio de aceptacion'], [['Linealidad', 'Respuesta vs concentracion', 'Curva de calibracion', 'R2 >= 0.995'], ['Precision', 'Reproducibilidad', 'RSD% (n=10)', 'RSD < 5%'], ['Exactitud', 'Cercania al valor real', 'CRM / recuperacion', '98-102%'], ['LOD', 'Minima detectable', '3 sigma blanco / S', '—'], ['LOQ', 'Minima cuantificable', '10 sigma blanco / S', '—']]);
  return {
    lessons: [
      L('Principios de ' + t, s + '-principios', TX(C4_TEXTS.intro(t) + validTable + H3('Fundamento instrumental') + P('Los instrumentos modernos de ' + t + ' constan de: 1) Fuente de radiacion (deuterio, tungsteno, laser). 2) Selector de longitud de onda (monocromador, red de difraccion). 3) Portamuestras. 4) Detector (fotomultiplicador, CCD, fotodiodo). 5) Sistema de procesamiento de datos.')), HL('Calibracion: Antes de cada sesion de medicion, verifica la calibracion con estandares certificados. Un error de calibracion invalida todos los resultados.')),
      L('Protocolo analitico', s + '-protocolo', TX(H('Procedimiento operativo estandar') + H3('1. Toma de muestra') + P('La muestra debe ser representativa del lote. Se recomienda tomar al menos 3 submuestras de diferentes puntos del lote y homogeneizarlas.') + H3('2. Preparacion de la muestra') + UL(['Digestion acida o alcalina segun la matriz.', 'Extraccion liquido-liquido o en fase solida.', 'Filtracion (0.45 micrometros) para eliminar particulas.', 'Dilucion a volumen conocido con solvente de calidad analitica.']) + H3('3. Curva de calibracion') + P('Preparar al menos 5 estandares de concentraciones crecientes que cubran el rango esperado. Cada estandar se mide por triplicado.') + H3('4. Medicion y control de calidad') + P('Las muestras se intercalan con estandares de control y blancos para verificar la ausencia de deriva instrumental y contaminacion cruzada.')),
        HL('Criterio de aceptacion: El coeficiente de correlacion R2 debe ser >= 0.995. Valores inferiores indican problemas en la preparacion de estandares o en el instrumento.', 'warning')),
      L('Laboratorio de validacion', s + '-lab', TX(H('Laboratorio de validacion analitica') + P('La validacion de metodos analiticos es un requisito fundamental en laboratorios acreditados bajo ISO 17025. En esta practica, desarrollaremos y validaremos un metodo espectrofotometrico completo.') + P('Cada parametro de validacion debe determinarse experimentalmente siguiendo protocolos estandarizados. La documentacion completa del proceso es esencial para la acreditacion del laboratorio.')), LAB({title: 'Validacion de metodo espectrofotometrico', objective: 'Validar un metodo analitico siguiendo la guia Eurachem 2014: linealidad, precision, exactitud, LOD, LOQ.', materials: 'Espectrofotometro UV-Vis, celdas de cuarzo, balanza analitica (+/-0.0001g), material volumetrico Clase A, CRM, software de datos.', steps: ['Preparar solucion stock de 1000 mg/L del analito.', 'Preparar 7 estandares de calibracion (0.5 a 15.0 mg/L).', 'Registrar el espectro de absorcion para determinar la longitud de onda optima.', 'Medir cada estandar por triplicado a la longitud de onda optima.', 'Construir la curva de calibracion y obtener la ecuacion de regresion.', 'Medir 10 blancos independientes para calcular LOD y LOQ.', 'Realizar pruebas de recuperacion a 3 niveles de concentracion.', 'Redactar el informe de validacion segun el formato Eurachem.']}), HL('Criterio de aceptacion: R2 >= 0.995, recuperacion entre 98-102%, RSD < 5%. Valores fuera de estos rangos requieren investigacion.', 'warning'),
        TX(H3('Procesamiento de datos') + P('Con los datos obtenidos, construye la curva de calibracion, calcula la ecuacion de regresion, determina LOD y LOQ, y calcula la incertidumbre combinada. Presenta todos los resultados en una tabla resumen.') + TBL(['Parametro', 'Resultado', 'Criterio', 'Cumple'], [['Linealidad (R2)', '0.9985', '>= 0.995', 'Si'], ['Precision (RSD%)', '2.3%', '< 5%', 'Si'], ['Recuperacion (%)', '100.2%', '98-102%', 'Si'], ['LOD (mg/L)', '0.15', '—', '—'], ['LOQ (mg/L)', '0.50', '—', '—']]))),
      L('Caso de estudio: Control de calidad', s + '-caso', TX(H('Caso practico: Control de calidad farmaceutico') + P('El control de calidad en la industria farmaceutica es un proceso riguroso que sigue las Buenas Practicas de Manufactura (GMP) y requiere metodos analiticos validados. A continuacion analizaremos un caso real.') + P('La capacidad de desarrollar y validar metodos analiticos es una habilidad fundamental para el quimico analitico moderno. Este caso te preparara para enfrentar situaciones reales en el laboratorio.')), CS({content: 'Un laboratorio farmaceutico recibe un lote de materia prima para la fabricacion de analgesicos. Debe verificarse que la concentracion del principio activo cumpla con las especificaciones (95-105% de lo declarado). Se requiere desarrollar y validar un metodo analitico.', questions: ['Que parametros de validacion son criticos para este caso?', 'Como estableces el plan de muestreo?', 'Que acciones tomas si los resultados estan fuera de especificacion?', 'Como documentas el proceso segun las BPM?']}), HL('Reflexion final: La calidad de un analisis depende tanto de la tecnica instrumental como de la competencia del analista. La formacion continua y la estandarizacion de procedimientos son esenciales.')),
      L('Interpretacion y calidad', s + '-calidad', TX(H('Aseguramiento de la calidad') + H3('Cartas de control') + P('Las cartas de control Shewhart permiten monitorear la estabilidad del metodo analitico. Se grafican los valores de un material de control versus el numero de mediciones.') + H3('Reglas de Westgard') + UL(['1-3s: Un valor fuera de 3 sigma (error aleatorio)', '2-2s: Dos valores consecutivos fuera de 2 sigma (error sistematico)', '10x: Diez valores consecutivos del mismo lado de la media (sesgo)']) + H3('Reporte de resultados') + P('Los resultados se reportan como: Valor +/- Incertidumbre (unidades), con un nivel de confianza del 95% (k=2). Ejemplo: 124.5 +/- 2.3 mg/L') + (nextTitle ? P('Proximo modulo: ' + nextTitle + '. Temas: tecnicas cromatograficas y espectrometria de masas.') : P('Modulo completado.'))),
        GL([{term: 'Validacion', definition: 'Confirmacion de que un metodo cumple los requisitos para un uso especifico.'}, {term: 'Trazabilidad', definition: 'Cadena ininterrumpida de calibraciones a un patron nacional.'}, {term: 'Incertidumbre expandida', definition: 'Intervalo que contiene el valor verdadero al 95% de confianza.'}, {term: 'Blanco analitico', definition: 'Muestra sin analito para detectar contaminacion.'}, {term: 'Selectividad', definition: 'Capacidad de medir el analito sin interferencia de otros componentes.'}])),
    ],
    summary: {concepts: ['Fundamento de ' + t, 'Instrumentacion', 'Validacion', 'Control de calidad'], formulas: ['A = epsilon * b * C (Beer-Lambert)', 'LOD = 3sigma / S', 'LOQ = 10sigma / S'], commonMistakes: ['No corregir el blanco', 'Usar curvas de calibracion fuera del rango lineal', 'No considerar el efecto matriz'], applications: ['Control calidad farmaceutico', 'Analisis ambiental', 'Laboratorio clinico']},
    curiosities: [{title: 'Precision extrema', content: 'La balanza mas precisa del mundo detecta cambios de 0.0000000001 gramos. Se usa para calibrar otras balanzas.', type: 'data'}, {title: 'Analisis en Marte', content: 'El rover Curiosity lleva un cromatografo de gases-espectrometro de masas para analizar compuestos organicos en la superficie marciana.', type: 'data'}],
  };
}

// ===== Generator for Course 5: Quimica Industrial y Seguridad =====
function genIndustrial(mod, mi, prevTitle, nextTitle) {
  var t = mod.title; var s = mod.slug;
  var varTable = TBL(['Variable', 'Instrumento', 'Rango tipico', 'Precision', 'Aplicacion'], [['Caudal', 'Rotametro', '0-100 L/min', '+/-0.5%', 'Control de flujo'], ['Temperatura', 'Termopar', '-40 a 400C', '+/-0.1C', 'Reactores'], ['Presion', 'Manometro', '0-10 bar', '+/-0.25%', 'Columnas'], ['Nivel', 'Radar', '0-5 m', '+/-1 mm', 'Tanques'], ['pH', 'Electrodo', '0-14', '+/-0.02', 'Neutralizacion']]);
  return {
    lessons: [
      L('Ingenieria de ' + t, s + '-ingenieria', TX(C5_TEXTS.intro(t) + varTable + H3('Balance de materia: Ejemplo resuelto') + P('Una columna de destilacion procesa 1000 kg/h de una mezcla etanol/agua al 30% en peso de etanol. El destilado sale con 85% de etanol y los fondos con 2% de etanol.') + P('Balance total: E = D + F. Balance de etanol: E * 0.30 = D * 0.85 + F * 0.02. Resolviendo: D = 336.6 kg/h, F = 663.4 kg/h.')), HL('En la industria, un error de balance puede significar perdidas millonarias. Siempre verifica que la suma de entradas sea igual a la suma de salidas.')),
      L('Seguridad en procesos', s + '-seguridad', TX(C5_TEXTS.safety(t) + H3('Ejercicio HAZOP') + P('Aplica la metodologia HAZOP a una bomba que transfiere acido sulfurico concentrado a un reactor. Considera las siguientes desviaciones:') + TBL(['Desviacion', 'Causa', 'Consecuencia', 'Recomendacion'], [['Alto caudal', 'Fallo valvula', 'Sobrecalentamiento', 'Valvula de seguridad'], ['Bajo caudal', 'Bomba obstruida', 'Reaccion incompleta', 'Filtro en linea'], ['Alta presion', 'Valvula cerrada', 'Rotura tuberia', 'Disco de ruptura'], ['Fuga', 'Sello defectuoso', 'Quemaduras', 'Deteccion de gases']])), HL('Accidente historico: Bhopal 1984 - Fuga de isocianato de metilo en India. Mas de 15,000 victimas. Causa: entrada de agua en un tanque de MIC por una valvula mal cerrada.', 'warning'),
        TX(H3('Plan de emergencia') + P('Toda instalacion debe contar con un plan de respuesta a emergencias que incluya: procedimientos de evacuacion, equipos de proteccion, puntos de reunion, protocolos de comunicacion y primeros auxilios.') + P('Realiza un simulacro de respuesta a una fuga de acido sulfurico identificando: las acciones inmediatas, el equipo necesario y las autoridades a notificar.')), IMG('Diagrama de respuesta a emergencias', '')),
      L('Normativa y regulacion', s + '-normativa', TX(H('Marco regulatorio internacional') + H3('REACH (Europa)') + P('Reglamento (CE) 1907/2006. Evalua la seguridad de todas las sustancias fabricadas o importadas en la UE en cantidades mayores a 1 ton/ano. Mas de 25,000 sustancias registradas.') + H3('OSHA PSM (EE.UU.)') + P('Estandar 29 CFR 1910.119. Aplica a procesos con mas de 10,000 lb de sustancias peligrosas.') + H3('ISO 45001:2018') + P('Sistema de gestion de seguridad y salud en el trabajo. Ciclo PHVA.')),
        HL('Auditoria: Las no conformidades se clasifican como mayores, menores y observaciones.')),
      L('Gestion ambiental y sostenibilidad', s + '-ambiente', TX(H('Quimica verde y economia circular') + H3('Los 12 principios de la quimica verde') + UL(['1. Prevenir residuos en lugar de tratarlos.', '2. Maximizar la economia atomica (incorporar todos los atomos al producto).', '3. Disenar sintesis con sustancias menos peligrosas.', '4. Disenar productos mas seguros y eficaces.', '5. Usar disolventes y condiciones inocuas.', '6. Disenar procesos energeticamente eficientes.', '7. Usar materias primas renovables.', '8. Evitar derivados innecesarios (protecciones/deprotecciones).', '9. Usar catalizadores en lugar de reactivos estequiometricos.', '10. Disenar productos que se degraden al final de su vida util.', '11. Monitorear en tiempo real para prevenir la formacion de residuos.', '12. Disenar procesos inherentemente seguros.']) + H3('Economia circular vs. lineal') + P('La economia circular busca mantener los recursos en uso el mayor tiempo posible, extrayendo el maximo valor mientras se recuperan y regeneran los productos al final de su vida util.')),
        CS({content: 'Eres el superintendente de seguridad de una planta quimica que produce cloro mediante electrolisis de salmuera (proceso cloro-alcali). La planta utiliza tecnologia de celdas de mercurio y debe migrar a tecnologia de membranas para 2026. Se ha reportado una fuga de 5 kg de cloro durante mantenimiento.', questions: ['Cuales son los principales riesgos de la tecnologia actual?', 'Que medidas inmediatas implementarias tras la fuga?', 'Como disenarias el plan de migracion?', 'Que indicadores monitorearias para verificar la seguridad post-migracion?']})),
      L('Proyecto integrador', s + '-proyecto', TX(H('Proyecto final: Diseno conceptual de planta quimica') + P('Disena el concepto basico de una planta quimica para producir un producto de tu eleccion.') + H3('Entregables') + OL(['Memoria descriptiva del proceso con reacciones, balances y condiciones.', 'Diagrama de flujo de proceso (PFD) mostrando equipos y corrientes.', 'Diagrama de tuberias e instrumentos (P&ID) de una seccion del proceso.', 'Analisis HAZOP de al menos 3 nodos criticos.', 'Evaluacion de impacto ambiental y plan de gestion de residuos.', 'Plan de seguridad industrial y respuesta a emergencias.', 'Analisis economico preliminar (CAPEX, OPEX, periodo de recuperacion).', 'Cronograma de implementacion (diagrama de Gantt).']) + (nextTitle ? P('Siguiente: ' + nextTitle + '. Continua construyendo tu formacion como ingeniero quimico.') : P('Curso completado!'))),
        GL([{term: 'PFD', definition: 'Process Flow Diagram. Muestra equipos principales y corrientes del proceso.'}, {term: 'P&ID', definition: 'Piping & Instrumentation Diagram. Detalla tuberias, valvulas e instrumentos.'}, {term: 'HAZOP', definition: 'Hazard and Operability Study. Metodologia para identificar peligros.'}, {term: 'CAPEX', definition: 'Inversion de capital en equipos e instalaciones.'}, {term: 'OPEX', definition: 'Gastos operativos de operacion y mantenimiento.'}])),
    ],
    summary: {concepts: ['Procesos de ' + t, 'Seguridad industrial', 'Gestion ambiental', 'Normativa'], formulas: ['Balance materia: Ent = Sal + Acum', 'ROI = (Beneficio/Inversion) x 100'], commonMistakes: ['Subestimar los costos de seguridad en el CAPEX', 'No considerar la disposicion final de residuos', 'Omitir la capacitacion del personal'], applications: ['Petroquimica', 'Farmacos', 'Tratamiento de aguas']},
    curiosities: [{title: 'La planta mas grande', content: 'La refinería de Jamnagar (India) procesa 1.24 millones de barriles de petroleo al dia. Es la mas grande del mundo.', type: 'data'}, {title: 'Innovacion verde', content: 'Novamont produce bioplasticos a partir de almidon de maiz y aceites vegetales. 150,000 ton/ano.', type: 'data'}],
  };
}

// ===== Public API =====
var GENERATORS = [genFundamentos, genGeneral, genOrganica, genAnalitica, genIndustrial];

function generateModuleContent(mod, mi, prevTitle, nextTitle, courseIndex) {
  var gen = GENERATORS[courseIndex];
  if (!gen) throw new Error('No generator for course index ' + courseIndex);
  return gen(mod, mi, prevTitle, nextTitle);
}

module.exports = { generateModuleContent: generateModuleContent, GENERATORS: GENERATORS, L: L, TX: TX, HL: HL, IMG: IMG, LAB: LAB, CS: CS, GL: GL };
